backend:
  name: git-gateway
  branch: master
media_folder: static/assets
public_folder: assets
collections:
  - name: articles
    label: Articles
    folder: articles
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor:
      preview: false
    fields:
      - { name: featured_image, label: Image, widget: image }
      - { name: date, label: Date, widget: datetime }
      - { name: tags, label: Tags, widget: list, default: ["article"] }
      - { name: author, label: Author }
      - { name: title_en, label: "Title (English)" }
      - { name: intro_en, label: "Introduction (English)" }
      - { name: body_en, label: "Body (English)", widget: markdown }
      - { name: title_es, label: "Título (Español)" }
      - { name: intro_es, label: "Introducción (Español)" }
      - { name: body_es, label: "Cuerpo (Español)", widget: markdown }
      - { name: title_de, label: "Titel (Deutsch)" }
      - { name: intro_de, label: "Einführung (Deutsch)" }
      - { name: body_de, label: "Textkörper (Deutsch)", widget: markdown }
      - { name: title_fr, label: "Titre (Français)" }
      - { name: intro_fr, label: "Introduction (Français)" }
      - { name: body_fr, label: "Corps (Français)", widget: markdown }
      - { name: title_it, label: "Titolo (Italiano)" }
      - { name: intro_it, label: "Introduzione (Italiano)" }
      - { name: body_it, label: "Corpo (Italiano)", widget: markdown }
      - { name: title_nl, label: "Titel (Nederlands)" }
      - { name: intro_nl, label: "Invoering (Nederlands)" }
      - { name: body_nl, label: "Hoofdtekst (Nederlands)", widget: markdown }