backend:
  name: git-gateway
  branch: master
media_folder: static/assets
public_folder: assets
collections:
  - name: pages
    label: Pages
    editor:
      preview: false
    files:
      - label: "Home"
        name: "home"
        file: "content/home.md"
        fields:
          - { name: "background_image", label: "Background image", widget: image }
          - name: "heading"
            label: "Heading"
            widget: object
            fields:
              - { name: english, label: English, widget: string }
              - { name: español, label: Español, widget: string }
              - { name: deutsch, label: Deutsch, widget: string }
              - { name: italiano, label: Italiano, widget: string }
              - { name: français, label: Français, widget: string }
          - name: "subheading"
            label: "Subheading"
            widget: object
            fields:
              - { name: english, label: English, widget: string }
              - { name: español, label: Español, widget: string }
              - { name: deutsch, label: Deutsch, widget: string }
              - { name: italiano, label: Italiano, widget: string }
              - { name: français, label: Français, widget: string }
          - name: "button_text"
            label: "Buton text"
            widget: object
            fields:
              - { name: english, label: English, widget: string }
              - { name: español, label: Español, widget: string }
              - { name: deutsch, label: Deutsch, widget: string }
              - { name: italiano, label: Italiano, widget: string }
              - { name: français, label: Français, widget: string }
  - name: articles
    label: Articles
    folder: articles
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor:
      preview: false
    fields:
      - { name: featured_image, label: Image, widget: image }
      - { name: date, label: Date, widget: datetime }
      - { name: tags, label: Tags, widget: list, default: ["article"] }
      - { name: author, label: Author }
      - name: "content_en"
        label: English
        widget: object
        fields:
          - { name: title_en, label: "Title" }
          - { name: intro_en, label: "Introduction" }
          - { name: body_en, label: "Body", widget: markdown }
      - name: "content_es"
        label: Español
        widget: object
        fields:
          - { name: title_es, label: "Título" }
          - { name: intro_es, label: "Introducción" }
          - { name: body_es, label: "Cuerpo", widget: markdown }
      - name: "content_de"
        label: Deutsch
        widget: object
        fields:
          - { name: title_de, label: "Titel" }
          - { name: intro_de, label: "Einführung" }
          - { name: body_de, label: "Textkörper", widget: markdown }
      - name: "content_fr"
        label: Français
        widget: object
        fields:
          - { name: title_fr, label: "Titre" }
          - { name: intro_fr, label: "Introduction" }
          - { name: body_fr, label: "Corps", widget: markdown }
      - name: "content_it"
        label: Italiano
        widget: object
        fields:
          - { name: title_it, label: "Titolo" }
          - { name: intro_it, label: "Introduzione" }
          - { name: body_it, label: "Corpo", widget: markdown }
      - name: "content_nl"
        label: Nederlands
        widget: object
        fields:
          - { name: title_nl, label: "Titel" }
          - { name: intro_nl, label: "Invoering" }
          - { name: body_nl, label: "Hoofdtekst", widget: markdown }
