export default {
	age: {
		en: "Age",
		es: "Edad",
		de: "Alter",
		it: "Età",
		fr: "Âge",
	},
	back_to_the_dogs: {
		en: "Back to the dogs",
		es: "De vuelta a los perros",
		de: "Zurück zu den Hunden",
		it: "Di nuovo ai cani",
		fr: "Retour aux chiens",
	},
	breed: {
		en: "Breed",
		es: "Raza",
		de: "Rasse",
		it: "Razza",
		fr: "Race",
	},
	can_you_help: {
		prefix: {
			en: "Can you help ",
			es: "¿Puedes ayudar a ",
			de: "Kannst du ",
			it: "Puoi aiutare ",
			fr: "Pouvez-vous aider ",
		},
		suffix: {
			en: "?",
			es: "?",
			de: " helfen?",
			it: "?",
			fr: "?",
		},
	},
	cant_adopt_or_foster: {
		prefix: {
			en:
				"If you can't adopt or foster but still want to help, you can! Please help us to spread the word about ",
			es:
				"Si no puede adoptar o fomentar pero aún quiere ayudar, ¡puede hacerlo! Ayúdenos a correr la voz sobre ",
			de:
				"Wenn Sie nicht adoptieren oder fördern können, aber trotzdem helfen möchten, können Sie! Bitte helfen Sie uns, ",
			it:
				"Se non puoi adottare o affidarti, ma vuoi comunque aiutare, puoi farlo! Aiutaci a spargere la voce su ",
			fr:
				"Si vous ne pouvez pas adopter ou favoriser mais que vous voulez toujours aider, vous pouvez! Aidez-nous à faire connaître ",
		},
		suffix: {
			en: " by using the buttons below...",
			es: " usando los botones a continuación ...",
			de: " über die folgenden Schaltflächen bekannt zu machen ...",
			it: " usando i pulsanti qui sotto ...",
			fr: " en utilisant les boutons ci-dessous ...",
		},
	},
	cat_friendly: {
		en: "Cat-friendly",
		es: "Amigable con los gatos",
		de: "Katzenfreundlich",
		it: "Amichevole con i gatti",
		fr: "Compatible avec les chats",
	},
	change_language_text: {
		en: "Change language",
		fr: "Changer de langue",
		de: "Sprache wechseln",
		it: "Cambia lingua",
		es: "Cambiar el idioma",
	},
	days: {
		en: "days",
		es: "dias",
		de: "Tage",
		it: "giorni",
		fr: "journées",
	},
	dog_friendly: {
		en: "Dog-friendly",
		es: "Amigable con los perros",
		de: "Hundefreundlich",
		it: "Amichevole con i cani",
		fr: "Convient aux chiens",
	},
	family_friendly: {
		en: "Family-friendly",
		es: "Familiar",
		de: "Familienfreundlich",
		it: "Famiglie",
		fr: "Conviviale et familiale",
	},
	find_a_home: {
		prefix: {
			en: "Please help us to find a home for ",
			es: "Ayúdenos a encontrar un hogar para ",
			de: "Bitte helfen Sie uns, ein Zuhause für ",
			it: "Aiutateci a trovare una casa per ",
			fr: "Aidez-nous à trouver un logement pour ",
		},
		suffix: {
			en: " by sharing this page with your family and friends.",
			es: " compartiendo esta página con su familia y amigos.",
			de:
				" zu finden, indem Sie diese Seite mit Ihrer Familie und Freunden teilen.",
			it: " condividendo questa pagina con la famiglia e gli amici.",
			fr: " en partageant cette page avec votre famille et vos amis.",
		},
	},
	find_out_more: {
		adoption: {
			en: "Find out more about the adoption process",
			es: "Obtenga más información sobre el proceso de adopción",
			de: "Erfahren Sie mehr über den Adoptionsprozess",
			it: "Scopri di più sul processo di adozione",
			fr: "En savoir plus sur le processus d'adoption",
		},
		fostering: {
			en: "Find out more about the fostering process",
			es: "Obtenga más información sobre el proceso de fomento",
			de: "Erfahren Sie mehr über den Förderprozess",
			it: "Scopri di più sul processo di promozione",
			fr: "En savoir plus sur le processus de placement",
		},
	},
	find_us: {
		en: "Find us on...",
		es: "Encuéntranos en...",
		de: "Finden Sie uns auf...",
		it: "Trovaci su...",
		fr: "Retrouvez-nous sur...",
	},
	in_care: {
		en: "in care",
		es: "en el cuidado",
		de: "in Pflege",
		it: "in cura",
		fr: "en soins",
	},
	licence_required: {
		en: "Licence required",
		es: "Licencia requerida",
		de: "Lizenz erforderlich",
		it: "Licenza richiesta",
		fr: "Licence requise",
	},
	location: {
		location: {
			en: "Location",
			es: "Ubicación",
			de: "Ort",
			it: "Posizione",
			fr: "Emplacement",
		},
		shelter: {
			en: "Shelter",
			es: "Perrera",
			de: "Tierheim",
			it: "Canile",
			fr: "Fourrière",
		},
		foster: {
			en: "Foster home",
			es: "Casa de acogida",
			de: "Pflegeheim",
			it: "Casa adottiva",
			fr: "Foyer d'accueil",
		},
		other: {
			en: "Other (see description)",
			es: "Otro (ver descripción)",
			de: "Andere (siehe Beschreibung)",
			it: "Altro (vedi descrizione)",
			fr: "Autre (voir description)",
		},
	},
	meet_the_dogs: {
		en: "Meet the dogs!",
		es: "¡Conozcan a los perros!",
		de: "Treffen Sie die Hunde!",
		it: "Incontra i cani!",
		fr: "Rencontrez les chiens!",
	},
	more_info: {
		en: "More information",
		es: "Más información",
		de: "Mehr Info",
		it: "Ulteriori informazioni",
		fr: "Plus d'informations",
	},
	no: {
		en: "No",
		es: "No",
		de: "Nein",
		it: "No",
		fr: "Non",
	},
	photos: {
		en: "Photos",
		es: "Fotos",
		de: "Fotos",
		it: "Fotografie",
		fr: "Photos",
	},
	sex: {
		sex: {
			en: "Sex",
			es: "Sexo",
			de: "Geschlect",
			it: "Sesso",
			fr: "Sexe",
		},
		M: {
			en: "Male",
			es: "Macho",
			de: "Männlich",
			it: "Maschio",
			fr: "Mâle",
		},
		F: {
			en: "Female",
			es: "Hembra",
			de: "Weiblich",
			it: "Femmina",
			fr: "Femelle",
		},
	},
	share: {
		en: "Share",
		es: "Compartir",
		de: "Teilen",
		it: "Condividere",
		fr: "Partager",
	},
	sterilised: {
		en: "Sterilised",
		es: "Esterilizado",
		de: "Sterilisiert",
		it: "Sterile",
		fr: "Stérilisé",
	},
	tbc: {
		en: "To be confirmed",
		es: "Por confirmar",
		de: "Noch zu bestätigen",
		it: "Da confermare",
		fr: "A confirmer",
	},
	time_in_care: {
		en: "Time in care",
		es: "Tiempo en cuidado",
		de: "Zeit in Pflege",
		it: "Tempo di cura",
		fr: "Temps de soins",
	},
	video_request: {
		en: "Contact us for video of",
		es: "Contáctanos para el video de",
		de: "Kontaktieren Sie uns für ein Video von",
		it: "Contattaci per il video di",
		fr: "Contactez-nous pour la vidéo de",
	},
	yes: {
		en: "Yes",
		es: "Sí",
		de: "Ja",
		it: "Sì",
		fr: "Oui",
	},
	registered_charity: {
		en: "Registered Charity in the Canary Islands since April 2013",
		es:
			"Sociedad benéfica registrada en las Islas Canarias desde abril de 2013",
		de:
			"Eingetragene Wohltätigkeitsorganisation auf den Kanarischen Inseln seit April 2013",
		it: "Carità registrata nelle Isole Canarie da aprile 2013",
		fr:
			"Organisme de bienfaisance enregistré aux îles Canaries depuis avril 2013",
	},
	website_by: {
		en: "Website by",
		es: "El sitio web de",
		de: "Website von",
		it: "Sito web di",
		fr: "Site web par",
	},
}
